FROM python:3.7
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
RUN groupadd djangogroup && useradd -m -g djangogroup -s /bin/bash django
ADD . /app
COPY ./local_run.sh /

